//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Item { get; set; }
        public string Count { get; set; }
        public string Price { get; set; }
    }
}
