//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class buhgalterEntities : DbContext
    {
        public buhgalterEntities()
            : base("name=buhgalterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buy> Buy { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Visa> Visa { get; set; }
    }
}
