//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Middle { get; set; }
        public string Last { get; set; }
        public string Phone { get; set; }
        public string Dol { get; set; }
        public string Price { get; set; }
    }
}
