//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visa
    {
        public int Id { get; set; }
        public string visa1 { get; set; }
        public string Doh { get; set; }
        public string Trat { get; set; }
        public string Ost { get; set; }
    }
}
